FROM alpine:3.13.0

WORKDIR /app

RUN apk update && apk add curl git

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN wget https://github.com/digitalocean/doctl/releases/download/v1.57.0/doctl-1.57.0-linux-amd64.tar.gz
RUN tar xf doctl-1.57.0-linux-amd64.tar.gz
RUN mv doctl /usr/local/bin

