FROM alpine:3.13.0

COPY requirements.txt /tmp/requirements.txt

RUN apk add --no-cache --virtual .build-deps \
    libc6-compat=1.2.2-r0 \
    alpine-sdk=1.0-r0 \    
    linux-headers=5.7.8-r0 \
    openssl-dev=1.1.1j-r0 \
    libffi-dev=3.3-r2 \
    python3=3.8.7-r1 \
    python3-dev=3.8.7-r1 \
    nginx=1.18.0-r13 \
    uwsgi=2.0.19.1-r1 \
    uwsgi-python3=2.0.19.1-r1 \
    git=2.30.1-r0 \    
    supervisor=4.2.1-r0 && \
    python3 -m ensurepip && \    
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    pip3 install --no-cache-dir -r /tmp/requirements.txt && \
    rm /etc/nginx/conf.d/default.conf && \
    rm -r /root/.cache

RUN apk add -U tzdata && \
    cp /usr/share/zoneinfo/Brazil/East /etc/localtime && \
    mkdir -p /var/log/app/ && \
    chmod 777 -R /var/log/app/